const mockTickets = [
  {
    id: "1",
    name: "Payment Failure Issue",
    status: "Waiting on contact",
    priority: "High",
    source: "Chat",
    owner: "Jane Cooper",
    createdDate: "04-07-2025",
    description: "Customer is unable to complete payment due to gateway error.",
  },
  {
    id: "2",
    name: "Product Inquiry",
    status: "Waiting on us",
    priority: "Medium",
    source: "Email",
    owner: "Wade Warren",
    createdDate: "04-07-2025",
    description:
      "Customer requested more details about product specifications and availability.",
  },
  {
    id: "3",
    name: "Subscription Upgrade",
    status: "New",
    priority: "High",
    source: "Chat",
    owner: "Brooklyn Simmons",
    createdDate: "08-04-2025",
    description:
      "User wants to upgrade from Basic to Premium subscription plan.",
  },
  {
    id: "4",
    name: "Refund Request - Order #456",
    status: "New",
    priority: "Low",
    source: "Phone",
    owner: "Leslie Alexander",
    createdDate: "08-04-2025",
    description:
      "Customer is requesting a refund for a mistakenly placed order.",
  },
  {
    id: "5",
    name: "Pricing Clarification",
    status: "Closed",
    priority: "Medium",
    source: "Chat",
    owner: "Jenny Wilson",
    createdDate: "08-04-2025",
    description:
      "Customer needed clarification on pricing tiers and billing cycle.",
  },
  {
    id: "6",
    name: "Login Not Working",
    status: "Waiting on us",
    priority: "Critical",
    source: "Phone",
    owner: "Guy Hawkins",
    createdDate: "04-07-2025",
    description:
      "User is locked out and cannot login despite correct credentials.",
  },
  {
    id: "7",
    name: "Feature Request: Reports",
    status: "Waiting on contact",
    priority: "High",
    source: "Phone",
    owner: "Robert Fox",
    createdDate: "08-04-2025",
    description:
      "Customer has requested a new reporting feature for user activity.",
  },
  {
    id: "8",
    name: "SLA Violation Complaint",
    status: "Closed",
    priority: "Medium",
    source: "Chat",
    owner: "Cameron Williamson",
    createdDate: "08-04-2025",
    description:
      "Complaint raised for delayed response violating the SLA terms.",
  },
  {
    id: "9",
    name: "Unable to Download Invoice",
    status: "New",
    priority: "Low",
    source: "Email",
    owner: "Savannah Nguyen",
    createdDate: "09-04-2025",
    description:
      "User is unable to download the invoice from the billing page.",
  },
  {
    id: "10",
    name: "Change Account Email",
    status: "Waiting on us",
    priority: "Medium",
    source: "Chat",
    owner: "Courtney Henry",
    createdDate: "10-04-2025",
    description: "Customer wants to update their registered email address.",
  },
  {
    id: "11",
    name: "Data Export Request",
    status: "New",
    priority: "High",
    source: "Phone",
    owner: "Theresa Webb",
    createdDate: "11-04-2025",
    description: "User has requested a complete export of account data.",
  },
  {
    id: "12",
    name: "Bug in Analytics Dashboard",
    status: "Waiting on contact",
    priority: "Critical",
    source: "Email",
    owner: "Marvin McKinney",
    createdDate: "12-04-2025",
    description: "Analytics dashboard displays incorrect figures since update.",
  },
  {
    id: "13",
    name: "Resend Verification Email",
    status: "Closed",
    priority: "Low",
    source: "Chat",
    owner: "Esther Howard",
    createdDate: "13-04-2025",
    description: "Customer didn’t receive verification email after signup.",
  },
  {
    id: "14",
    name: "Account Compromised",
    status: "New",
    priority: "Critical",
    source: "Phone",
    owner: "Dianne Russell",
    createdDate: "14-04-2025",
    description: "User reports unauthorized access to their account.",
  },
  {
    id: "15",
    name: "Mobile App Crash",
    status: "Waiting on contact",
    priority: "High",
    source: "Chat",
    owner: "Kristin Watson",
    createdDate: "15-04-2025",
    description: "App crashes on login screen on Android devices.",
  },
  {
    id: "16",
    name: "Question About Discounts",
    status: "Closed",
    priority: "Medium",
    source: "Email",
    owner: "Ronald Richards",
    createdDate: "16-04-2025",
    description: "Customer asked about eligibility for seasonal discount.",
  },
  {
    id: "17",
    name: "Unable to Upload File",
    status: "Waiting on us",
    priority: "High",
    source: "Chat",
    owner: "Eleanor Pena",
    createdDate: "17-04-2025",
    description: "Upload feature fails with a 'timeout' error.",
  },
  {
    id: "18",
    name: "Question About GDPR",
    status: "New",
    priority: "Medium",
    source: "Email",
    owner: "Jacob Jones",
    createdDate: "18-04-2025",
    description: "User asked for GDPR compliance documentation.",
  },
  {
    id: "19",
    name: "Browser Compatibility Issue",
    status: "Closed",
    priority: "Low",
    source: "Phone",
    owner: "Floyd Miles",
    createdDate: "19-04-2025",
    description: "Site doesn’t render properly on older versions of Safari.",
  },
  {
    id: "20",
    name: "Accessibility Concern",
    status: "New",
    priority: "Medium",
    source: "Chat",
    owner: "Arlene McCoy",
    createdDate: "20-04-2025",
    description:
      "Customer provided feedback about screen reader accessibility.",
  },
  {
    id: "21",
    name: "Multi-language Support Request",
    status: "Waiting on contact",
    priority: "High",
    source: "Email",
    owner: "Jerome Bell",
    createdDate: "21-04-2025",
    description: "User asked whether platform will support Spanish interface.",
  },
  {
    id: "22",
    name: "Legal Documentation Needed",
    status: "Closed",
    priority: "Medium",
    source: "Phone",
    owner: "Kathryn Murphy",
    createdDate: "22-04-2025",
    description: "Request for terms and conditions and privacy policy PDF.",
  },
  {
    id: "23",
    name: "Auto-renewal Cancellation",
    status: "Waiting on us",
    priority: "Low",
    source: "Email",
    owner: "Devon Lane",
    createdDate: "23-04-2025",
    description: "User wants to stop upcoming subscription auto-renewal.",
  },
  {
    id: "24",
    name: "Add Team Member to Account",
    status: "New",
    priority: "Medium",
    source: "Chat",
    owner: "Annette Black",
    createdDate: "24-04-2025",
    description: "Customer needs help adding team members to their account.",
  },
];

export default mockTickets;
